name: Example Build & Deploy to GitHub Pages
on:
  push:
    branches:
      - master
    tags:
      - v1
    paths:
      - 'website/**'
      - 'docs/**'
      - '.github/**'
  repository_dispatch:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout  🛎️
        uses: actions/checkout@v7
        with:
          persist-credentials: false
      - name: Setup pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 10.22.0
      - name: use Node.js 22
        uses: actions/setup-node@v7
        with:
          node-version: '22.x'
          cache: 'pnpm'
      - name: npm script 🔧
        run: |
          pnpm install --frozen-lockfile --registry=https://registry.npmjs.com
          npm run build:website
        env:
          CI: true
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: website/dist
          GIT_CONFIG_NAME: ${{ secrets.GIT_CONFIG_NAME}}
          GIT_CONFIG_EMAIL: ${{ secrets.GIT_CONFIG_EMAIL}}
